### ISSUE TITLE
is this like an ai for hearthstone?

### ISSUE THREAD

**Issue by JunkyardCat** [HearthSim/SabberStone#11]
like you give it some state and it gives a solution?

**Comment by darkfriend77** [comment]
It's a simulator of hearthstone ... which can be used for your case ...Check the SabberstoneCoreAi project .. It contains an AI which search best moves for a current state ... Feel free to ask more ... Am 06.04.2017 06:27 schrieb JunkyardCat <notifications@github.com>:like you give it some state and it gives a solution?

**Comment by darkfriend77** [comment]
btw. you can always contact us on Discord (Hearthsim) for questions ...
