### ISSUE TITLE
bug of SabberStoneGui

### ISSUE THREAD

**Issue by jklasdf** [HearthSim/SabberStone#121]
1. make a deck
2. select its deck
3. push "Start Game" button
4. System.ArgumentNullException

**Comment by rnilva** [comment]
Thank you for reporting this bug. It seems SabberGui uses `Game.Hash()` but unfortunately it is temporary unavailable so it causes the error. I will work on this problem soon!

**Comment by jklasdf** [comment]
Thanks.
This bug is fixed.
