### ISSUE TITLE
Molten Blade cost doesn't change upon transformation

### ISSUE THREAD

**Issue by hgorelick** [HearthSim/SabberStone#155]
In other words, when Molten Blade transforms, the new weapon's cost remains 1. I looked at the ChangeEntityTask and ChangeEntityBlock and I'm not sure what is causing this.

**Comment by rnilva** [comment]
Hi!
I conducted a simple test for this issue in the current master branch but can't reproduce this issue. 
```csharp
		[Fact]
		public static void TransformationInHand()
		{
			var game = new Game(new GameConfig
			{
				StartPlayer = 1,
				FillDecks = true,
				FillDecksPredictably = true,
				Shuffle = false,
			});
			game.StartGame();

			IPlayable blade = Generic.DrawCard(game.Player1, Cards.FromName("Molten Blade"));
			IPlayable scroll = Generic.DrawCard(game.Player1, Cards.FromName("Shifting Scroll"));
			IPlayable zerus = Generic.DrawCard(game.Player1, Cards.FromName("Shifter Zerus"));

			game.EndTurn();
			game.EndTurn();

			// Next Turn
			Assert.Equal(blade.Cost, blade.Card.Cost);
			Assert.Equal(scroll.Cost, scroll.Card.Cost);
			if (zerus.AuraEffects.AdaptiveCostEffect != null)
				Assert.Equal(zerus.Cost, zerus.Card.Cost);

			game.EndTurn();
			game.EndTurn();

			// Next Turn
			Assert.Equal(blade.Cost, blade.Card.Cost);
			Assert.Equal(scroll.Cost, scroll.Card.Cost);
			if (zerus.AuraEffects.AdaptiveCostEffect != null)
				Assert.Equal(zerus.Cost, zerus.Card.Cost);
			Assert.Equal(zerus.Cost, zerus.Card.Cost);
		}
```

If you use a different branch and if the test fails on your side, can I see the `ChangeEntityBlock` and `AuraEffect.cs`?
Thanks!

**Comment by hgorelick** [comment]
Hi Milva,

Thanks for the quick response. The test works as expected. It must be a bug
in my AI. I'm looking into it.

Thanks again!

**Comment by hgorelick** [comment]
I take that back. I've set some breakpoints to check if the cost is correct and something weird is happening:

If I set a breakpoint after calling game.Clone(), then the cost of the transformed Molten Blade in the cloned game is incorrect. But, if I step through game.Clone(), then the cost is correct...
