### ISSUE TITLE
Upcoming mechanic changes to Multi-Target Cards

### ISSUE THREAD

**Issue by winnowerhs** [HearthSim/SabberStone#166]
https://news.blizzard.com/en-us/hearthstone/23037180/hearthstone-update-july-1-preparing-for-saviors-of-uldum

> Multi-Target Cards: We’ve updated the following multi-target cards to function even if there is only one viable target on the board. These cards will now also properly trigger when played by random effects such as Yogg’Saron.
> 
> Dark Bargain
> Cleave
> Multishot
> Forked Lightning

**Comment by rnilva** [comment]
CardDef update would fix this automatically.
