### ISSUE TITLE
Game Point of View of Player

### ISSUE THREAD

**Issue by SethKitchen** [HearthSim/SabberStone#177]
I want to represent the game state in binary, but if I just Deserialize the *Model.Game* object, this will include the opponent's hand zone and ?deck? which should be private. Is there a way to get the *Model.Game* with opponent data private/unincluded?

Thanks for help and for making this amazing framework.

**Comment by rnilva** [comment]
Hello!
I assume you need a `Model.Game` object W/ partial information.

Currently, we don't have fancy API for that, but there is a way to make `Model.Game` partially observable.
Here is a function we used for another project:
```csharp
        private static readonly Dictionary<GameTag, int> PlaceHolder = new Dictionary<GameTag, int>(0);
        private static Game CreatePartiallyObservableGame(Game fullGame)
        {
            Game game = fullGame.Clone();
            SabberStoneCore.Model.Entities.Controller op = game.CurrentOpponent;
            SabberStoneCore.Model.Zones.HandZone hand = op.HandZone;
            ReadOnlySpan<IPlayable> span = hand.GetSpan();
            for (int i = span.Length - 1; i >= 0; --i)
            {
                hand.Remove(span[i]);
                hand.Add(new Unknown(in op, PlaceHolder, span[i].Id));
            }
            game.AuraUpdate();
            span = op.DeckZone.GetSpan();
            for (int i = 0; i < span.Length; i++)
                span[i].ActivatedTrigger?.Remove();
            var deck = new SabberStoneCore.Model.Zones.DeckZone(op);
            for (int i = 0; i < span.Length; i++)
            {
                span[i].ActivatedTrigger?.Remove();
                deck.Add(new Unknown(in op, PlaceHolder, span[i].Id));
            }
            op.DeckZone = deck;
            return game;
        }
```

So basically it just replaces cards in the opponent's hand and deck with `new Unknown()` object and remove related triggers, and updated auras.

I think you can use the function before you deserialise game objects.
Let me know if any problem has occurred.

**Comment by SethKitchen** [comment]
Thanks this is exactly what I was looking for.

**Comment by SethKitchen** [comment]
I use .Net Framework so I can integrate with Python using pythonnet and couldn't use System.Memory for ReadOnlySpan . I did this translation (also blocking current user's unknown deck). Hope it's right.

    	private static readonly Dictionary<GameTag, int> PlaceHolder = new Dictionary<GameTag, int>(0);
		private static Game CreatePartiallyObservableGame(Game fullGame)
		{
			Game game = fullGame.Clone();
			SabberStoneCore.Model.Entities.Controller op = game.CurrentOpponent;
			SabberStoneCore.Model.Entities.Controller p = game.CurrentPlayer;
			SabberStoneCore.Model.Zones.HandZone hand = op.HandZone;
			int opHandCount = hand.Count;
			for(int i=0; i<opHandCount; i++)
			{
				int id = hand[0].Id;
				hand.Remove(0);
				hand.Add(new Unknown(in op, PlaceHolder, id));
			}
			game.AuraUpdate();
			int opDeckCount = op.DeckZone.Count;
			for(int i=0; i<opDeckCount; i++)
			{
				int id = op.DeckZone[i].Id;
				op.DeckZone[i].ActivatedTrigger?.Remove();
				op.DeckZone.Remove(0);
				op.DeckZone.Add(new Unknown(in op, PlaceHolder, id));
			}
			int myDeckCount = p.DeckZone.Count;
			for (int i = 0; i < myDeckCount; i++)
			{
				int id = p.DeckZone[i].Id;
				p.DeckZone[i].ActivatedTrigger?.Remove();
				p.DeckZone.Remove(0);
				p.DeckZone.Add(new Unknown(in p, PlaceHolder, id));
			}
			return game;
		}
