### ISSUE TITLE
How to use Unity3D client?

### ISSUE THREAD

**Issue by suchadet1964** [HearthSim/SabberStone#182]
Hello

On the readme, there is a screenshot of the Unity3D client + server.
How do we use it? 
There is this repository https://github.com/darkfriend77/SabberStone-gRPC from @darkfriend77  but I can't find the client.

Thank you very much

**Comment by darkfriend77** [comment]
![image](https://user-images.githubusercontent.com/17710198/84862787-1a2be280-b074-11ea-8a05-4a1f90c29867.png)
