### ISSUE TITLE
Asynchronous games

### ISSUE THREAD

**Issue by rnilva** [HearthSim/SabberStone#31]
Hi,

First of all, I am not used to TPL/PLINQ syntax but still working learning and practicing about them.
I tried making several copies of a game using `Game.Clone()` method and making tasks for each. Then I attempted `async` method and `await Task.WhenAll()`, or Just tried `Monitor.TryEnter` / `Finally` statement.
Definitely neither of them works. Even in locking syntax I was not sure which object I should lock.

Questions:
1. Is there any way to run N games asynchronously? 
2. Is the internal structure of the `Class Game` not allow asynchronous tasks?

I am on #Hearthsim most of the time so if you guys could provide any kind of help that would be awesome.
Milva#2618

**Comment by darkfriend77** [comment]
Hi,If you clone a game it is detached an will be asyncron .... can you show me the use case or the code you are using?The clone in sabberstone makes a deep copy of the game ... there is no relation to the parent game ... Task.WhenAll or Monitor.TryEnter arent part of Sabberstone dont know in which context you are using it.I can help more if I see a code fragment and an use case.:-)Am 21.07.2017 10:09 schrieb rnilva <notifications@github.com>:Hi,
First of all, I am not used to TPL/PLINQ things but working practices and learning.
The situation is, first, I tried making several copies of a game using Game.Clone() method and making tasks for each. And attempted async method and await Task.WhenAll(), or Just tried Monitor.TryEnter / Finally statement.
Definitely neither was working. Even in latter case I was not sure which object I should lock.
Question:
Is there any way to run N games asynchronously?Is the internal structure of the Class Game not allow asynchronous tasks?
I am connected to #Hearthsim most of the time so any answers via Discord are very welcomed.
Milva#2618

**Comment by rnilva** [comment]
Hi, Thank you for replying.
I'm currently working on implementing a rudimentary MCTS AI. I want to generate many games to simulate for the same start position to improve its performance.

```csharp
        public static PlayerTask Search(Game g)
        {
            var root = new Node(g);
            var timer = Stopwatch.StartNew();
            var count = 0;
            while (timer.Elapsed < TimeSpan.FromSeconds(10))
            {
                var leaf = TreePolicy(root);
                var reward = Rollout(leaf);
                root = Backup(leaf, reward);
                count += 1;
            }
            return BestChild(root, 0).Action;
        }

        static double Rollout(Node n)
        {
            var current = n.Clone();
            var rnd = new Random();
            while (!current.IsTerminal)
            {
                current.Game.Process(current.LegalActions[rnd.Next(current.LegalActions.Count)]);
            }
           return current.Game.ControllerById(AgentId).PlayState == PlayState.WON ? 1.0 : 0.0;
        }
public class Node : IEquatable<Node>
    {
        public Game Game { get; set; }
        public List<PlayerTask> LegalActions => Game.CurrentPlayer.Options();
        List<String> ActionsTried = new List<string>();

        public string Hash => Game.Hash(GameTag.LAST_CARD_PLAYED, GameTag.ENTITY_ID);
        public Node Parent;
        public List<Node> Children { get; set; } = new List<Node>();
        public double VisitCount;
        public double QValue;

        public PlayerTask Action;

        public bool IsTerminal => Game.State == State.COMPLETE;
        public bool IsFullyExpanded => LegalActions.Count == ActionsTried.Count;
        public Node Clone()
        {
            var clone = (Node)this.MemberwiseClone();
            clone.Game = this.Game.Clone();
            return clone;
        }
```
The code above works well in one thread. I want to make the `Rollout` method asynchronous.
I tried code like this:
```csharp
        private static void DefaultPolicy(Node n, int simLimit = 500)
        {
            for (var i = 0; i < simLimit; i++)
            {
                var rnd = new Random();
                n.Game.Process(n.LegalActions[rnd.Next(n.LegalActions.Count)]);
                if (n.IsTerminal)
                    break;
            }
        }
        static async void UnifromRandomRollouts(Node n, double ensemblecount = 3.0)
        {
            var ensemble = new List<Node>();
            var tasks = new List<Task>();
            for (var i = 0; i < ensemblecount; i++)
            {
                ensemble.Add(n.Clone());
            }
            foreach (var node in ensemble)
            {
                tasks.Add(new Task(() => DefaultPolicy(node)));
            }
            await Task.WhenAll(tasks);
        }
```
Which is failed.

**Comment by darkfriend77** [comment]
Hmm ... I will need to take a closer look ... technicaly it shoild be possible ... however I havent looked at asyncron stuff sofar ... are you on discord?Am 21.07.2017 1:29 nachm. schrieb rnilva <notifications@github.com>:Hi, Thank you for replying.
I'm currently working on implementing a rudimentary MCTS AI. I want to generate many games to simulate for the same start position to improve its performance.
        public static PlayerTask Search(Game g)
        {
            var root = new Node(g);
            var timer = Stopwatch.StartNew();
            var count = 0;
            while (timer.Elapsed < TimeSpan.FromSeconds(10))
            {
                var leaf = TreePolicy(root);
                var reward = Rollout(leaf);
                root = Backup(leaf, reward);
                count += 1;
            }
            return BestChild(root, 0).Action;
        }

        static double Rollout(Node n)
        {
            var current = n.Clone();
            var rnd = new Random();
            while (!current.IsTerminal)
            {
                current.Game.Process(current.LegalActions[rnd.Next(current.LegalActions.Count)]);
            }
           return current.Game.ControllerById(AgentId).PlayState == PlayState.WON ? 1.0 : 0.0;
        }
public class Node : IEquatable<Node>
    {
        public Game Game { get; set; }
        public List<PlayerTask> LegalActions => Game.CurrentPlayer.Options();
        List<String> ActionsTried = new List<string>();

        public string Hash => Game.Hash(GameTag.LAST_CARD_PLAYED, GameTag.ENTITY_ID);
        public Node Parent;
        public List<Node> Children { get; set; } = new List<Node>();
        public double VisitCount;
        public double QValue;

        public PlayerTask Action;

        public bool IsTerminal => Game.State == State.COMPLETE;
        public bool IsFullyExpanded => LegalActions.Count == ActionsTried.Count;
        public Node Clone()
        {
            var clone = (Node)this.MemberwiseClone();
            clone.Game = this.Game.Clone();
            return clone;
        }
The code above works well in one thread. I want to make the Rollout method asynchronous.
I tried code like this:
        private static void DefaultPolicy(Node n, int simLimit = 500)
        {
            for (var i = 0; i < simLimit; i++)
            {
                var rnd = new Random();
                n.Game.Process(n.LegalActions[rnd.Next(n.LegalActions.Count)]);
                if (n.IsTerminal)
                    break;
            }
        }
        static async void UnifromRandomRollouts(Node n, double ensemblecount = 3.0)
        {
            var ensemble = new List<Node>();
            var tasks = new List<Task>();
            for (var i = 0; i < ensemblecount; i++)
            {
                ensemble.Add(n.Clone());
            }
            foreach (var node in ensemble)
            {
                tasks.Add(new Task(() => DefaultPolicy(node)));
            }
            await Task.WhenAll(tasks);
        }
Which is failed.

**Comment by rnilva** [comment]
@darkfriend77 
I sent you PM.

In the meantime, I tried the code below:
```csharp
        static async void UnifromRandomRollouts(Node n)
        {
            var games = new ConcurrentBag<Game>();
            //Envinronment.ProcessorCount
            for (var i = 0; i < 8; i++)
                games.Add(n.Game.Clone());
            await Task.Run(() => Parallel.ForEach(games, g => { RandomGame(g); }));
            foreach (var game in games)
            {
                n.Delta += (game.ControllerById(AgentId).PlayState == PlayState.WON) ? 1.0 : 0.0;
            }
            n.Delta /= 8.0;
        }
        private static void RandomGame(Game g, int simLimit = 500)
        {
            for (var i = 0; i < simLimit; i++)
            {
                var rnd = new Random();
                var options = g.CurrentPlayer.Options();
                var option = options[rnd.Next(options.Count)];
                g.Process(option);
                if (g.State == State.COMPLETE)
                    break;
            }
        }
```
Which intentionally uses only the Game class, and failed too.

**Comment by Bert-Proesmans** [comment]
If this is discussed on Discord, please use the HearthSim channel, because there are more people who can benefit from the information (including myself).

**Comment by darkfriend77** [comment]
Jep ... lets discuss it on discord ... you got the channel?Am 21.07.2017 5:57 nachm. schrieb Proesmans Bert <notifications@github.com>:If this is discussed on Discord, please use the HearthSim channel, because there are more people who can benefit from the information (including myself).
