### ISSUE TITLE
novice overhaul

### ISSUE THREAD

**Issue by Bert-Proesmans** [HearthSim/SabberStone#32]
While working on the kettle integration I noticed there is a high entry barrier when starting out with the project, at least for me.
That's why I suggest overhauling the code (and especially interfaces of models) to have a more intuitive and documented design. The intention is to transform, not to rebuild.
To commence this operation i have created tasks which will guide the process. Any additional suggestions will be edited into THIS message to track it's progress.

The following invariants are important to the process:

- Discussions about interface changes will be held in a separate issue, which will be linked from this thread.

- This overhaul should not fail any existing test cases. Changing test code in this context MUST be preceded by a discussion!

Development will happen inside a separate branch until most/all tasks are completed.

- [x] Setup CI - Travis/AppVeyor.

- [x] Revert targeted frameworks (of each project) to MAJOR-MINOR versions. In the case of .NET Standard the lowest version possible.

- [x] Group enums under SabberStoneCore.Enums namespace.

- [ ] Move all Kettle related code (SabberStoneCore.Kettle namespace) from the core project.

- [ ] Fix all errors occurring in compilation/testing.

- [ ] For all interfaces, pick the most general interface type to hold public properties.

- [x] Document interfaces of the most crucial components (Models).

- [ ] Overhaul model interfaces to be more intuitive.

**Comment by darkfriend77** [comment]
Sounds good, can we disscuss the points on discord? I'm not sure if I did understand them right.

**Comment by mvegter** [comment]
As for CI I would recommend using appveyor. It tries to find the unit tests (if not specified) and runs them. Travis is good but (correct me) doesn't support C# natively.

**Comment by Bert-Proesmans** [comment]
Regarding CI; Both are setup to have some assurance the project does run on both Linux and Windows platforms. 
Specifically about unit tests, AppVeyor's auto-find functionality is limited, so we still need to manually instruct an instance to run the tests. At the moment running tests is hardcoded for SabberStoneCoreTest, which is unfortunate. Does anyone know of another good approach?

**Comment by darkfriend77** [comment]
Hmm ... I'm not really deep into CI I'm using Jenkins a lot ... but nothing else ... so I let you guys decide ...Am 31.07.2017 20:16 schrieb Proesmans Bert <notifications@github.com>:Regarding CI; Both are setup to have some assurance the project does run on both Linux and Windows platforms.
Specifically about unit tests, AppVeyor's auto-find functionality is limited, so we still need to manually instruct an instance to run the tests. At the moment running tests is hardcoded for SabberStoneCoreTest, which is unfortunate. Does anyone know of another good approach?

**Comment by Bert-Proesmans** [comment]
A lot of properties have a colliding name with their type, especially enum typed properties. eg property Choice.ChoiceType has type ChoiceType which makes it difficult to properly target one or the other when both parent namespaces are loaded. [related code](https://github.com/HearthSim/SabberStone/blob/52ba23e20fa86d6d4cf2397df92d11800c3620d1/SabberStoneCore/Model/Choice.cs#L22) 
To resolve this i suggest using a naming scheme for the enum types so the property names themselves don't need to change. 
Prefixing each enum name with an uppercase e sounds like the least amount of effort and preserves the original name of each enum, similar to the interface naming convention (which prefixes with uppercase i).

For the given example this would become
```csharp
public class Choice
{
    // [...]
    public EChoiceType ChoiceType {get; set;} = EChoiceType.INVALID;
    // [...]
}
```

**Comment by darkfriend77** [comment]
I'm not really voting for prefixing enums ... also looking for naming conventions fo c sharp it seems not to be a common practice ... Is it that disturbing, having the properties named that same as there type?

```csharp
...Choice.ChoiceType = ChoiceType.SUMMON;
```

**Comment by Bert-Proesmans** [comment]
Our perspective is strongly influenced by the fact that we develop within an IDE (Visual Studio) which resolves type references for us and colours the type names appropriately. We can easily understand the context of the code by interpreting these colours.

The exact problem is lack of clarity.
Lack of clarity within code of the same class and lack of clarity when someone else is using the library by writing his own code/wrappers. When a name of a type (or namespace) collides with another name and both are used within the same file it's not immediately obvious what is referred without context.

I used the word type explicitly because this is ALSO an issue with classes. I can easily imagine someone writing his wrapper and calling it `Game` as well, which leads to inconvenience when SabberStoneCore.Model.Game is imported next. 
eg 
```csharp
class Entity {
    Game Game {get; set;}
}
```
I do understand that this renaming causes confusion and give you, @darkfriend77, the last word in this matter. This is my last post mentioning the renaming of types.

In case of negative feedback:

- [ ] The E prefix for enums will be removed, which is easily done since all enums are already collected and referenced.

In case of positive feedback:

- [ ] The SabberStone.Model classes and possibly other public types will also receive a prefix, probably something in trend of Sabber[TypeName], like SabberGame.

**Comment by rnilva** [comment]
Is there a comparison table? I wonder if there are changes in GameTag.

**Comment by Bert-Proesmans** [comment]
Closing because the topic doesn't apply anymore
