### ISSUE TITLE
Damage and Armor interaction

### ISSUE THREAD

**Issue by Bert-Proesmans** [HearthSim/SabberStone#33]
I was looking at Character<T>::TakeDamage and noticed the damage to inflict first passes armor after which it's bound to the Predamage property. 
Shouldn't it be the other way around; Firsts predamage and then reducing the amount of armor?
[Related code](https://github.com/HearthSim/SabberStone/blob/52ba23e20fa86d6d4cf2397df92d11800c3620d1/SabberStoneCore/Model/Character.cs#L89-L109)

It would be an ideal moment to test with Prophet Velen.

**Comment by Bert-Proesmans** [comment]
Also, Character::TakeHeal doesn't have a pre-heal property. This might also be a case where Prophet Velen would fail.

**Comment by darkfriend77** [comment]
Shouldn't it be the other way around; Firsts predamage and then reducing the amount of armor?

You're right, but probablly not in the way you think about ... PreDamage is only used for IceBlock ... and of course armor has to be counted in ... and shouldn't be touched if it's a leathal damage ...

https://github.com/HearthSim/SabberStone/commit/33e7c119ae63dcac17f525c4edda2a58d71e3ab4

Concerning [EX1_350] Prophet Velen, it isn't implemented, at the moment, but that is probably to solve over a tag which sets to double ... like spelldamage ...
