### ISSUE TITLE
Minion Placement on Summon

### ISSUE THREAD

**Issue by Juhlinus** [HearthSim/SabberStone#53]
Minions summoned by Doppelgangster and Sindragosa are not positioned correctly.

**Comment by Bert-Proesmans** [comment]
darkfriend77 said `I added the functionality ^^ :smiley: however I haven't done the fix but ... I can look at it ^^ :smiley:`, which means placement on summon can now be chosen.
fixes for these specific minions are pending.

**Comment by darkfriend77** [comment]
It's fixed https://github.com/HearthSim/SabberStone/commit/63cea58cb0eb6c405cce1177714170ff4b5ba88f

However we need to verify how default summons are working, for example a deathrattle summon.

**Comment by darkfriend77** [comment]
fixed, for all cards.

check https://github.com/HearthSim/SabberStone/commit/6c7ea40c97c5e8f64a081547e26dfba056e8a4ee
