### ISSUE TITLE
What happened to Stove?

### ISSUE THREAD

**Issue by danielzuegner** [HearthSim/SabberStone#56]
Hi all,

I wanted to run SabberStone with the "real" HS client and noticed that the [URL to Stove](https://github.com/HearthSim/hearthsim.info/blob/master/stove) is down.

Has it moved or was it discontinued?

Thanks in advance!

**Comment by Bert-Proesmans** [comment]
Hi,
The project still exists privately. It also wasn't updated in some time, but it received attention again a few days ago. It's at the moment not in a state where it would just 'work' to play games.
Come join us at the developer discord if you want to talk about it, see [here](https://hearthsim.info/join/).

**Comment by chucklu** [comment]
Is it possible to run with real Hearthstone Client without Stove? @darkfriend77

**Comment by darkfriend77** [comment]
Nope,we are currently working on an own client.RegardsAm 16.07.2019 07:38 schrieb Chuck Lu <notifications@github.com>:Is it possible to run with real Hearthstone Client without Stove? @darkfriend77

**Comment by chucklu** [comment]
@darkfriend77  Do  you have a schedule when to release your own client? Is it open source?

@rnilva What did you mean in https://github.com/HearthSim/SabberStone/issues/164? Do yo have a solution to run the code with the game?

**Comment by darkfriend77** [comment]
A 80% implementation might be ready in a few weeks.RegardsAm 16.07.2019 09:48 schrieb Chuck Lu <notifications@github.com>:@darkfriend77  Do  you have a schedule when to release your own client? Is it open source?
@rnilva What did you mean in #164? Do yo have a solution to run the code with the game?
