### ISSUE TITLE
Hunter secrets

### ISSUE THREAD

**Issue by rnilva** [HearthSim/SabberStone#58]
- [x] Freezing Trap should increase its target's cost by 2 
- [x] Flare should not activate opponent's Cat Trick #60 
- [x] Explosive Trap should be activated regardless of the attacking minion's statues.
- [x] Freezing Trap and Misdirection should not be activated when the attacking minion died due to earlier activation of Explosive Trap

**Comment by darkfriend77** [comment]
There are a few possibilities to solve the current issue of the execution order.

- find a way to trigger from gametags and keep the right order
- play with fast execution
- create a new possibilities which can get an order into events which trigger on the same gametag (layered triggering)

**Comment by rnilva** [comment]
#71
