### ISSUE TITLE
Trigger/Enchant exception during StartGame

### ISSUE THREAD

**Issue by odkken** [HearthSim/SabberStone#59]
Running a simulated game with basic setup
![image](https://user-images.githubusercontent.com/3037938/29626066-6df00dfa-87e2-11e7-9851-c954845506db.png)

exception:
![image](https://user-images.githubusercontent.com/3037938/29626088-82a61da2-87e2-11e7-8f1d-4e38804fdcf5.png)

Triggers.Count == 0 at the time of the exception

call stack:
![image](https://user-images.githubusercontent.com/3037938/29626144-b52d8fb2-87e2-11e7-80d7-65bfe6003776.png)

**Comment by darkfriend77** [comment]
you should use 
`var options = game.CurrentPlayer.Options();`
instead of 
`var options = game.CurrentOpponent.Options();`

**Comment by odkken** [comment]
yeah i realized that after, but the exception was thrown before that executed.
