### ISSUE TITLE
GamePlay Update 9.2 check if implemented

### ISSUE THREAD

**Issue by darkfriend77** [HearthSim/SabberStone#83]
Gameplay & Updates

Hearthstone Mechanics Update – We've changed some underlying rules to prevent Wild Pyromancer from triggering off of Mindgames, and Djinni of Zephyrs from triggering off Entomb. Please check out the Upcoming Mechanics Update blog for details!
Several Friends List options have been bundled into a sub-menu.
Spells that are canceled by Counterspell will now trigger any “Whenever you cast a spell” and “After you cast a spell” effects.
Lord Jaraxxus no longer triggers Repentance, Sacred Trial, and Snipe.
Unlicensed Apothecary now reads: “After you summon a minion, deal 5 damage to your hero.” It will no longer activate from any Evolve effects.
It is no longer possible to cancel Choose One cards before the choices appear, this should resolve issues where the Choose One effect could be canceled too easily.
Hearthstone’s engine has been updated to Unity version 5.6.
Animations for Mimic Pod, Chromaggus, Shifting Shade, Ghastly Conjurer, and Cutpurse should no longer have a long pause.
Mana-cost reductions on cards such as Dragon’s Breath, Solemn Vigil, Everyfin is Awesome, and Obsidian Shard will now apply after all other mana cost changes, such as the effects from cards like Naga Sea Witch.

**Comment by rnilva** [comment]
"We've changed some underlying rules to prevent Wild Pyromancer from triggering off of Mindgames, "
This is not correctly implemented now.
